// src/components/ui/Heading.tsx
import { cn } from '@util/utils';

type HeadingProps =
	| {
			title: string;
			description?: string;
			centered?: boolean;
	  }
	| {
			title?: string;
			description: string;
			centered?: boolean;
	  };

export const Heading: React.FC<HeadingProps> = ({
	title,
	centered,
	description,
}) => {
	return (
		<div className={cn({ 'text-center': centered })}>
			{title && (
				<h2 className='text-2xl md:text-4xl font-special font-bold tracking-tight text-muted-background'>
					{title}
				</h2>
			)}
			{description && (
				<p className='text-sm md:text-base mt-1 text-muted-foreground'>
					{description}
				</p>
			)}
		</div>
	);
};

// src/lib/components/ui/Heading.svelte
<script>
	export let title = '';
	export let description = '';
	export let centered = false;
</script>

<div class:text-center={centered}>
	{#if title}
		<h2 class="text-2xl md:text-4xl font-special font-semibold tracking-tight">
			{title}
		</h2>
	{/if}
	{#if description}
		<p class="text-sm md:text-base mt-1">
			{description}
		</p>
	{/if}
	<hr class="my-6 border-t-2 border-gray-200" />
</div>
